import mongoose from 'mongoose';

const ProductSchema = new mongoose.Schema({
    category: String,
    attributes: [String],
    customerRating: Number,
    customerRatingImage: String,
    image: String,
    name: String,
    price: Number,
    productId: {type: Number, unique: true },
    shortDescription: String,
    url: String,
});

export const initProducts = async () => {
    return Product.create([
        {
            category: 'Utensils',
            attributes: ['utensils', 'utensil', 'cutlery', 'tableware', 'kitchen utensil'], 
            customerRating: 5.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/5.gif',
            image: 'https://i5.walmartimages.com/asr/9e57414d-89b1-467f-8796-cff2a8cd01f6_1.e1f69edc563fdc1dbe72c9dae32e7174.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'To-Go Ware Eco-Friendly Reusable Bamboo Kids Spoons and Forks- Set of 6',
            price: 11.99,
            productId: 482592454,
            shortDescription: 'To-Go Ware Eco-Friendly Reusable Bamboo Kids Spoons and Forks- Set of 6.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FTo-Go-Ware-Eco-Friendly-Reusable-Bamboo-Kids-Spoons-and-Forks-Set-of-6%2F482592454%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Utensils',
            attributes: ['utensils', 'utensil', 'cutlery', 'tableware', 'kitchen utensil'], 
            customerRating: 4.75,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/4_8.gif',
            image: 'https://i5.walmartimages.com/asr/a1ddd25b-af22-4eea-96cb-8435630160a1_3.bff0713898feaceacb95d3ed3f46f16c.png?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Ayesha Curry Eco Friendly Parawood Cooking Tool Set, 4-Piece',
            price: 22.48,
            productId: 56092797,
            shortDescription: 'Constructed from eco-friendly parawood, the tools are finished with food-grade, matte mineral oil to highlight the distinctive, beautiful wood grain. Mix up the ingredients for Ayeshas Citrus-Olive Oil cake or simmer down some brown sugar, soy sauce and ginger for Oven Roasted Brown Sugar Chicken with these indespensible kitchen tools designed for long-lasting comfort and durability, recipe after recipe.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FAyesha-Curry-Eco-Friendly-Parawood-Cooking-Tool-Set-4-Piece%2F56092797%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Utensils',
            attributes: ['utensils', 'utensil', 'cutlery', 'tableware', 'kitchen utensil'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/c45cabdb-2554-40c1-b00f-796ae6706b04_1.756634e0b16b3fc75ce66a3a7e24cfd9.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'BalsaCircle 100 pcs 6\" Disposable Natural Birch Wooden Forks - Eco Friendly Biodegradable Compostable Wedding Party Tableware',
            price: 4.31,
            productId: 887578362,
            shortDescription: 'Complete your tablescape with an attention to every little detail, including the place setting. Your guests will be so pleasantly surprised to find you have taken even this small consideration on their behalf! What you get:Each order is for one hundred (100) forks. Each fork measures 6in; long x 1in; wide.Material: 100% Compostable Birch Wood.No glazes, bleaches, or dyes.This purchase is for disposable forks only, other decorations are not included.PLEASE NOTE: This item is not returnable to Walmart.com or Walmart stores.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FBalsaCircle-100-pcs-6-Disposable-Natural-Birch-Wooden-Forks-Eco-Friendly-Biodegradable-Compostable-Wedding-Party-Tableware%2F887578362%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi'
        },
        {
            category: 'Utensils',
            attributes: ['utensils', 'utensil', 'cutlery', 'tableware', 'kitchen utensil'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/911f6d2b-3cef-4f7c-8791-a777d3140120_1.cdaebe5bb7a49988847408c63ff4e597.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Eco-Products 7\" Plant Starch Forks, Natural White, 1000 / Carton (Quantity)',
            price: 56.58,
            productId: 14982968,
            shortDescription: 'Cutlery is made of plant starch material, a renewable resource, and offers strength and heat tolerance. Ideal for hot foods and liquids. Heat tolerance is up to 200 degrees Fahrenheit. Reinforced handles provide extra strength. Cutlery is not recommended for microwaves and is not compostable.Eco-Products 7&quot; Plant Starch Forks, Natural White, 1000 / Carton (Quantity)',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FEco-Products-7-Plant-Starch-Forks-Natural-White-1000-Carton-Quantity%2F14982968%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi'
        },
        {
            category: 'Utensils',
            attributes: ['utensils', 'utensil', 'cutlery', 'tableware', 'kitchen utensil'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/316c80f6-564e-41ea-b8af-8df5c9a8fccb_1.1d7365df25fa10d0c29935345c39841c.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Brheez Disposable Cornstarch Forks - Eco Friendly Alternative to Plastic - Plant Based Cornstarch - Biodegradable Compostable - Heavy Weight - 7\" Ivory (Pack of 250)',
            price: 26.99,
            productId: 219643455,
            shortDescription: 'Brheez Disposable Cornstarch Forks - Eco Friendly Alternative to Plastic - Plant Based Cornstarch - Biodegradable Compostable - Heavy Weight - 7&quot; Ivory (Pack of 250)',
            url: 'http://c.affil.walmart.com/t/api02?l=http%3A%2F%2Fwww.walmart.com%2Fip%2F219643455%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi'
        },

        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/74674ff5-745b-46dc-8421-11042ca93ba6_1.9f86c8af50de0b403be6e7b6e2c352aa.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff',
            name: 'Champion Men\'s Double Dry Eco Fleece Crew',
            price: 20,
            productId: 141956605,
            shortDescription: '1x1 rib with spandex, Set-in armholes, Double-needle stitching.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FChampion-Men-s-Double-Dry-Eco-Fleece-Crew%2F141956605%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/8248200f-c832-4527-bd83-217845fdbfc6_1.6692faca9a01cec674f06306bf55fe2a.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Ladies Thin Blue Line Flag Vertical Back Print Alternative Apparel Eco Fleece Full Zipper Hooded Sweatshirt - Small',
            price: 69.99,
            productId: 344328227,
            shortDescription: 'Ladies Thin Blue Line Flag Vertical Back Print Alternative Apparel Eco Fleece Full Zipper Hooded Sweatshirt - Small',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FLadies-Thin-Blue-Line-Flag-Vertical-Back-Print-Alternative-Apparel-Eco-Fleece-Full-Zipper-Hooded-Sweatshirt-Small%2F344328227%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/3b4d27fd-70ad-4bea-95d2-54b772efc7cf_1.081d7cdb0238e596f3891e5465e6bc2f.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Champion Eco Men\'s Crewneck Shirt - White - Small',
            price: 28.48,
            productId: 186322768,
            shortDescription: 'Color : White 50% cotton, 50% polyester; made with recycled polyester fibers from plastic bottles; durable coverstitching throughout; set-in sleeves; heavy rib knit waistband and cuffs; logo at left cuff;KEY FEATURES- 50% cotton, 50% polyester.- Made with up to',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FChampion-Eco-Men-s-Crewneck-Shirt-White-Small%2F186322768%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 5.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/5.gif',
            image: 'https://i5.walmartimages.com/asr/7fc157d7-83b1-4b0c-8713-8667251057ae_1.818d63d078b6b87f58b696d89d5374fc.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'SoSoft Wool Dryer Balls for Baby Clothes 6 pack 100% Premium So Soft Wool Dryer Balls XXL Handmade in Nepal All Natural Eco Friendly All Natural Fabric Softener Natural Fabric Softener 6 Count Package',
            price: 13.95,
            productId: 122607959,
            shortDescription: 'Go green and spend less time in the laundry and dryer room knowing that you will have the perfect set of babies laundry with SoSoft 100% Wool Dryer Balls, 6-pack set. SoSoft Dryer Balls are expected to last for at least 1,000 laundry loads and are made from 100% hypoallergenic hand-spun wool to help save time, money, and stress on the environment by eliminating',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FSoSoft-Wool-Dryer-Balls-Baby-Clothes-6-pack-100-Premium-Soft-Wool-Dryer-Balls-XXL-Handmade-Nepal-Natural-Eco-Friendly-Natural-Fabric-Softener-Natural%2F122607959%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/a648c719-4d41-4ed0-8ded-82d92d4338d1_1.e24fd003b8844ecc41c545869e6861e1.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: '2117 of Sweden Svedje Eco Multisport XC Ski Pants Womens',
            price: 39.95,
            productId: 753298576,
            shortDescription: 'These pants are for serious cross country ski lovers, but go ahead and wear them for all your outdoor fun. 2117 of Sweden Women&rsquo;s Svedje Multi-sport pants are made with ripstop m&eacute;lange fabric with tons of stretch for great mobility when you are playing in the snow. Quick-drying fabric lets you work up a sweat without getting uncomfortable. The Hybrid Svedje pant is part of the 2117 Eco-friendly collection which designs apparel with the intention of reducing mankind&rsquo;s effect on our environment. Don\'t forget to grab the Svedge jacket to complete the look. 2117 of Sweden design and produce high quality sportswear with a clean Scandinavian design and generally run small. If you are between sizes, consider buying a size larger.Polyester ripstop and stretchy melange fabricEco-friendlyQuick-drying',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2F2117-of-Sweden-Svedje-Eco-Multisport-XC-Ski-Pants-Womens%2F753298576%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },

        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/a648c719-4d41-4ed0-8ded-82d92d4338d1_1.e24fd003b8844ecc41c545869e6861e1.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: '2117 of Sweden Svedje Eco Multisport XC Ski Pants Womens',
            price: 39.95,
            productId: 753298576,
            shortDescription: 'These pants are for serious cross country ski lovers, but go ahead and wear them for all your outdoor fun. 2117 of Sweden Women&rsquo;s Svedje Multi-sport pants are made with ripstop m&eacute;lange fabric with tons of stretch for great mobility when you are playing in the snow. Quick-drying fabric lets you work up a sweat without getting uncomfortable. The Hybrid Svedje pant is part of the 2117 Eco-friendly collection which designs apparel with the intention of reducing mankind&rsquo;s effect on our environment. Don\'t forget to grab the Svedge jacket to complete the look. 2117 of Sweden design and produce high quality sportswear with a clean Scandinavian design and generally run small. If you are between sizes, consider buying a size larger.Polyester ripstop and stretchy melange fabricEco-friendlyQuick-drying',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2F2117-of-Sweden-Svedje-Eco-Multisport-XC-Ski-Pants-Womens%2F753298576%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Clothing',
            attributes: ['clothing','outerwear', 'clothes', 'sleeve'], 
            customerRating: 0.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/558a0ef2-9e9f-43dc-96aa-f9e609ab4082_1.0e0a813e783875f7a516b904f5519b70.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Hanes ComfortBlend; Eco Smart; Crewneck Men\'s T-Shirt, Color: Oxford Grey, Size: L --- PACK OF 2 (Men\'s Athleticwear)',
            price: 15.2,
            productId: 187790050,
            shortDescription: 'Now our soft cotton-blend men\'s T-shirt is better than ever before: It\'s an EcoSmart&reg; shirt! That means it\'s made with up to 5% polyester created from recycled plastic bottlesComfortBlend&acirc;&bdquo;&cent; jersey fabric combines 50% cotton/50% polyester, specially knit for softnessLay Flat Collar stays flat, keeps its shapeguaranteed!Durable double stitching reinforces neck, sleeves, and hem',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FHanes-ComfortBlend-Eco-Smart-Crewneck-Men-s-T-Shirt-Color-Oxford-Grey-Size-L-PACK-OF-2-Men-s-Athleticwear%2F187790050%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },

        {
            category: 'Bags',
            attributes: ['bags','handbag', 'bag', 'tote bag', 'shoulder bag', 'luggage and bags'], 
            customerRating: 3.636,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/3_6.gif',
            image: 'https://i5.walmartimages.com/asr/001a0078-06e4-4816-9abf-2a0c47fb636a_1.e71780147b672ba0af82cff6e04f3a2a.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Reusable Shopping Bags Eco Foldable Trolley Tote Grocery Cart Storage - Set of 4',
            price: 13.88,
            productId: 835907883,
            shortDescription: 'The perfect set for your groceries. Very convenient and sturdy.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FReusable-Shopping-Bags-Eco-Foldable-Trolley-Tote-Grocery-Cart-Storage-Set-of-4%2F835907883%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Bags',
            attributes: ['bags','handbag', 'bag', 'tote bag', 'shoulder bag', 'luggage and bags'], 
            customerRating: 3.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/3.gif',
            image: 'https://i5.walmartimages.com/asr/a1b88529-7f35-4055-aaf0-5c59ba7b22fa_1.82b1adcbe60b25468cd524485f728406.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'TRISONIC Reusable Shopping Bag Grocery Tote Laundry Bags Eco Friendly Foldable Large New',
            price: 5.61,
            productId: 112414487,
            shortDescription: 'New Foldable Shopping BagThis tote is a must have to those that care about the environment!Have it always handy in your bag, car or at home.Features: * Reusable* Eco-friendly* Practical* Lightweight* Easy to fold* Canvas* Reinforced Base* Color: Random color will be sent. Available in blue, black, red and green.* Dimension Opened: 14.5&quot; L x 13.5&quot; x 6&quot; D* Handle size: 12&quot; long',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FTRISONIC-Reusable-Shopping-Bag-Grocery-Tote-Laundry-Bags-Eco-Friendly-Foldable-Large-New%2F112414487%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Bags',
            attributes: ['bags','handbag', 'bag', 'tote bag', 'shoulder bag', 'luggage and bags'], 
            customerRating: 3.623,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/3_6.gif',
            image: 'https://i5.walmartimages.com/asr/c33c341d-6e57-4a68-a2c6-ec1da0f93d64_1.57feb0e99e1b969cabe59b2b8bc278e7.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'FileMate ECO 14\" G230 Laptop/Notebook Carrying Bag, Assorted Colors',
            price: 7.65,
            productId: 21983583,
            shortDescription: 'The lightweight and form-fitting FileMate ECO 14&quot; G230 Laptop/Notebook carring&nbsp;bag offers improved protection to your tablet. The bag is also lined with a padded material to protect the screen and body. This bag features a convenient front pouch that holds extra accessories. It is also security checkpoint friendly with durable zippers for easy access to your device. With convenient carrying handles, you can easily take it anywhere you go.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FFileMate-ECO-14-G230-Laptop-Notebook-Carrying-Bag-Assorted-Colors%2F21983583%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Bags',
            attributes: ['bags','handbag', 'bag', 'tote bag', 'shoulder bag', 'luggage and bags'],  
            customerRating: 3.974,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/4.gif',
            image: 'https://i5.walmartimages.com/asr/c2c0bedb-9203-493a-9b07-b700b631f7c5_1.64c0b20ea989b5d973eb8026066efd84.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'FileMate ECO 17\" G230 Laptop/Notebook Carrying Bag, Assorted Colors',
            price: 10.98,
            productId: 21983595,
            shortDescription: 'The lightweight and form-fitting FileMate ECO 17&quot; G230 Laptop/Notebook carring&nbsp;bag offers improved protection to your tablet. The bag is also lined with a padded material to protect the screen and body. This bag features a convenient front pouch that holds extra accessories. It is also security checkpoint friendly with durable zippers for easy access to your device. With convenient carrying handles, you can easily take it anywhere you go.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FFileMate-ECO-17-G230-Laptop-Notebook-Carrying-Bag-Assorted-Colors%2F21983595%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Bags',
            attributes: ['bags','handbag', 'bag', 'tote bag', 'shoulder bag', 'luggage and bags'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/9a1d38b2-b017-4068-9f42-f8d2fb66e82d_1.ccfe1d5b4215f33b8edcd54231e6f24e.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: '3 Pieces LIGHT ECO FRIENDLY SHOPPING BAGS FOLDABLE BACKPACK TRAVEL GROCERY REUSABLE',
            price: 12.95,
            productId: 602865356,
            shortDescription: '2 Handle Bags (in Brown and orange) and 1 Convertible Backpack (in evergreen) are Great for Commuters, the Farmer&rsquo;s Market, the Gym, Traveling or for Grocery Shopping',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2F3-Pieces-LIGHT-ECO-FRIENDLY-SHOPPING-BAGS-FOLDABLE-BACKPACK-TRAVEL-GROCERY-REUSABLE%2F602865356%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },

        {
            category: 'Detergents',
            attributes: ['detergents','laundry detergent', 'detergent'], 
            customerRating: 4.694,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/4_7.gif',
            image: 'https://i5.walmartimages.com/asr/db1470b3-7266-499d-b85c-1a65d4f86f11_1.02cb9ab34cdb46b6a7ea1fc745440711.png?odnHeight=450&odnWidth=450&odnBg=ffffff',
            name: '(2 pack) ECOS Liquid Laundry Detergent Free & Clear, 128 Oz',
            price: 23.69,
            productId: 279062531,
            shortDescription: 'ECOS Liquid Laundry Detergent Free &amp; Clear, with plant-derived cleaning power. Gentle on clothes, skin. Hypoallergenic. 128oz value-size.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2F2-pack-ECOS-Liquid-Laundry-Detergent-Free-Clear-128-Oz%2F279062531%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Detergents',
            attributes: ['detergents','laundry detergent', 'detergent'], 
            customerRating: 4.674,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/4_7.gif',
            image: 'https://i5.walmartimages.com/asr/1f645873-b198-4d9f-8f8c-64f5bccb4f88_1.890c18e929cfb56db18bd03f5276bf2b.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'ECOS 2X Ultra Natural Laundry Detergent, Lavender, 170 Loads',
            price: 13.38,
            productId: 31346591,
            shortDescription: 'Get your clothes really clean with ECOS Natural Laundry Detergent. Its formula is a simple one, combining high-quality ingredients for a product that works well with colors, whites and virtually any other fabric. It is hypoallergenic, so you can trust it not to irritate sensitive skin. This lavender laundry detergent has a built-in fabric softener to keep your fabrics feeling soft while helping you save you money. Its scents are made with aromatic natural fragrances and essential oils. ECOS laundry detergent also uses a concentrated formula with plant-derived cleaning agents for an earth-friendly recipe. Versatile and functional, this detergent works well in hot and cold water and with HE and standard washing machines.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FECOS-2X-Ultra-Natural-Laundry-Detergent-Lavender-170-Loads%2F31346591%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Detergents',
            attributes: ['detergents','laundry detergent', 'detergent'], 
            customerRating: 5.0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/5.gif',
            image: 'https://i5.walmartimages.com/asr/e18f7937-1183-47d0-9ae0-fad6027672f8_1.47f0d6a3d1d78c23580c70a6316e7475.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Tide Liquid Laundry Detergent Eco-Box, Original Scent, 105 fl oz, 96 loads',
            price: 19.94,
            productId: 189468871,
            shortDescription: 'Tide Eco-Box is the same liquid laundry detergent you love but even more powerful. Made with 30% less water, its re-engineered formula gives you more cleaning per drop than Tide Original liquid detergent in a 150 fl oz bottle, plus it&rsquo;s smaller and easier to store. It&rsquo;s compressed into a shipping-safe package made from 60% less plastic and features a No-Drip twist tap minimizing any leaks and spills. There&rsquo;s also a ramp built within the packaging to make sure you can use every drop of detergent. To assemble Tide Eco-Box, simply pull the tab on the side of the pack to reveal the tap and dosing cup. In case you don&rsquo;t have an edge, there&rsquo;s a built-in stand on the bottom of the box. More importantly, it&rsquo;s easy to use! Just twist the blue knob counter clockwise to dispense the desired amount. Make sure to twist slowly so the detergent doesn&rsquo;t come out too quickly.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FTide-Liquid-Laundry-Detergent-Eco-Box-Original-Scent-105-fl-oz-96-loads%2F189468871%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Detergents',
            attributes: ['detergents','laundry detergent', 'detergent'], 
            customerRating: 4.632,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/4_6.gif',
            image: 'https://i5.walmartimages.com/asr/9625ed70-0c21-4047-ae86-777651486e51_1.a9004620e6350b90f66af96b8efb8dac.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'ECOS 2X Ultra Natural Laundry Detergent, Magnolia & Lily, 170 Loads',
            price: 24.29,
            productId: 31015729,
            shortDescription: 'The formula for ECOS? laundry detergent is simple: high-quality ingredients + low price + a little love = our best seller! Perfect for colors, whites, and all fabrics, ECOS? has a built-in fabric softener to save you money. Concentrated formula with plant-derived cleaning agents. All scents made with aromatic natural fragrances and essential oils. Hypoallergenic. Great for hot and cold water, HE and standard machines.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FECOS-2X-Ultra-Natural-Laundry-Detergent-Magnolia-Lily-170-Loads%2F31015729%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Detergents',
            attributes: ['detergents','laundry detergent', 'detergent'], 
            customerRating: 3.889,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/3_9.gif',
            image: 'https://i5.walmartimages.com/asr/04dd6ebc-8eda-4f2e-b420-743e9e6d8220_1.3b03a3e122124f6713fc076fa5d0a5b2.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Disney Baby ECOS Lavender & Chamomile Laundry Detergent, 128 oz',
            price: 13.99,
            productId: 49211698,
            shortDescription: 'Specially designed for baby, Disney Baby ECOS Lavender &amp; Chamomile Laundry Detergent is crafted from plant-based ingredients. Hypoallergenic and carefully pH balanced, it is wonderfully kind to baby\'s sensitive skin. What\'s good for baby is also good for the environment. Safely free of phosphates, formaldehyde and petrochemicals, Disney Baby ECOS is also harmless in septic or greywater systems, quickly biodegrades and even has a recyclable bottle and cap. Give your family the silky comfort and softness of the Hundred Acre Wood. Each time you and your little one feel the delicate touch of freshly cleaned clothing or bedding, it\'s as if the Hundred Acre Wood has sent a gift of delight to go be you wherever you are--together.',
            url: 'https://i5.walmartimages.com/asr/04dd6ebc-8eda-4f2e-b420-743e9e6d8220_1.3b03a3e122124f6713fc076fa5d0a5b2.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
        },

        {
            category: 'Soaps',
            attributes: ['soaps','soap', 'bar soap'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/74fa346f-e336-4254-8ee3-e997ae1dd0b4_1.8a86ca1cd4524652c7cdeac428b96645.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'RDI-USA ECO BY GREEN CULTURE BATH SOAP BAR, 1 OZ., 300 BARS PER CASE',
            price: 88.39,
            productId: 666280171,
            shortDescription: 'Eco by Green Culture Collection: Uses raw materials based on renewable plant materials, is almost entirely biodegradable, and utilizes well-tolerated food colors. In addition, it contains no silicone oils, paraffin and other questionable additives. The fresh, green scent with its aromas of invigorating lemon, captivating jasmine, and warm amber offers an appealing and attractive note. The result: gentle, skin-friendly formulations that are suited even to sensitive skin. &lt;br&gt; 1 oz. bar&lt;br&gt;',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FRDI-USA-ECO-BY-GREEN-CULTURE-BATH-SOAP-BAR-1-OZ-300-BARS-PER-CASE%2F666280171%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Soaps',
            attributes: ['soaps','soap', 'bar soap'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/dbafcda4-2367-4573-b450-659ae31dc2a1_1.2fe27d4dba23b499006d41f726a50627.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Eco Pure cleansing Bath Soap Lot of 18 each 1oz Bars',
            price: 20,
            productId: 728944021,
            shortDescription: 'Eco pure Cleansing Bath soap',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FEco-Pure-cleansing-Bath-Soap-Lot-of-18-each-1oz-Bars%2F728944021%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Soaps',
            attributes: ['soaps','soap', 'bar soap'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/b2f82472-4959-491d-b5fb-381ab30c141a_1.7aea39bfb1746f4842811984621017ec.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Eco Pure cleansing Bath Soap Lot of 4 each 1oz Bars. Total of 4oz',
            price: 9,
            productId: 822458559,
            shortDescription: 'Eco Pure cleansing Bath Soap Lot of 4 each 1oz Bars. Total of 4oz',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FEco-Pure-cleansing-Bath-Soap-Lot-of-4-each-1oz-Bars-Total-of-4oz%2F822458559%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Soaps',
            attributes: ['soaps','soap', 'bar soap'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/144e3f91-7b65-4ee2-bf99-fb2c4f78e1d1_1.4057cb13241d838b2b728525a65a3d44.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'DIVERSIFIED ECO BOTANICS BODY BAR, 28 G. SACHET, 500 BARS PER CASE',
            price: 98.56,
            productId: 429750710,
            shortDescription: 'Enriched with Organic olive oil, the attractive Eco Botanics line brings a fresh feel to any guestroom. It features salon quality formulations, gently comforting on skin and hair. The moisturizing body and cleansing bars are vegetable based with a refreshing chamomile and honey fragrance. The shampoo, conditioner, lotion, and body wash are infused with soothing white tea and nourishing honey. Eco Botanics, especially designed with our EcoWell commitment, is a perfect earth-conscious and affordable choice for hotels and resorts in any locale. &lt;br&gt; Chamomile &amp; Honey Formula with Organic Olive Oil, Paraben &amp; Gluten Free &lt;br&gt; 28 g. Soap in Sachet&lt;br&gt;',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FDIVERSIFIED-ECO-BOTANICS-BODY-BAR-28-G-SACHET-500-BARS-PER-CASE%2F429750710%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Soaps',
            attributes: ['soaps','soap', 'bar soap'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/65c893bc-b7e6-4eb7-bcb0-8ee3f03fc98e_1.d66b254568ae1bd0dc2bff59a12f564a.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Bio Natura Sustainable Vegetal Soap - Argan Oil & Wild Hay 8.8oz',
            price: 12.88,
            productId: 140795941,
            shortDescription: 'Bio Natura Sustainable Vegetal Soap - Argan Oil &amp; Wild Hay 8.8oz',
            url: 'https://i5.walmartimages.com/asr/65c893bc-b7e6-4eb7-bcb0-8ee3f03fc98e_1.d66b254568ae1bd0dc2bff59a12f564a.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
        },

        {
            category: 'Lighting',
            attributes: ['lighting', 'light bulb', 'incadescent light bulb', 'light'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/5ae88eb6-414c-40fc-8dc6-9984ee5a6879_1.57019b96a507d17015c51b7671cdbb38.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Pack Of 6 38PAR20/NFL 120V 38 Watt High Output (50W Replacement) 38W PAR20 Narrow Flood 120 Volt Halogen Par 20 Eco Light Bulbs',
            price: 19.99,
            productId: 136262404,
            shortDescription: '38-Watt PAR20 flood light light bulb 6 pack is ideal for use in living rooms, bedrooms, hallways, bathrooms, dining rooms, offices, kitchens. Sterl Lighting bulbs are a bright, energy saving alternative to standard incandescent light bulbs. It provides a bright, white wide beam of light which is ideal for general room, accenting art and architecture, as well as enhancing your outdoor landscaping. They reduce energy consumption without sacrificing the qualities of a traditional bulb and produce high quality light more efficiently. Fully dimmable, this energy saving household light bulb contains no mercury and replaces your current 50 Watt incandescent, saving you up to 28% in energy costs. Use them in your existing fixtures just as you would standard incandescent and your home will look great while you save energy.',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FPack-Of-6-38PAR20-NFL-120V-38-Watt-High-Output-50W-Replacement-38W-PAR20-Narrow-Flood-120-Volt-Halogen-Par-20-Eco-Light-Bulbs%2F136262404%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Lighting',
            attributes: ['lighting', 'light bulb', 'incadescent light bulb', 'light'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/3bef5a85-7d52-4a5f-9799-854d6ffdbcaf_1.58fa8171406ceedc4eb24d252d6c1b64.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'Bioluz LED A19 6w (40 Watt Equivalent) ECO Series Soft White (2700K) Light Bulbs 6-Pack',
            price: 19.79,
            productId: 343489179,
            shortDescription: 'Bioluz LED A19 6w (40 Watt Equivalent) ECO Series Soft White (2700K) Light Bulbs 6-Pack (BA19-2-6WW6)',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FBioluz-LED-A19-6w-40-Watt-Equivalent-ECO-Series-Soft-White-2700K-Light-Bulbs-6-Pack%2F343489179%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Lighting',
            attributes: ['lighting', 'light bulb', 'incadescent light bulb', 'light'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/f66e0136-0461-4d33-a13f-42c35f553988_1.08569a2b5eb47fbc83751492fd450d85.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF',
            name: 'G9 Halogen Bulb, 40 Watt - 2 Pack - Energy Saving - Dimmable - Soft White 2700K - 120V - Q40, CL, T4 JD Type, Clear Light Bulb, Eco Efficient G9.., By Brite Innovations',
            price: 8.89,
            productId: 576939701,
            shortDescription: 'Household Essentials/Light Bulbs/All Light Bulbs',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FG9-Halogen-Bulb-40-Watt-2-Pack-Energy-Saving-Dimmable-Soft-White-2700K-120V-Q40-CL-T4-JD-Type-Clear-Light-Bulb-Eco-Efficient-G9-Brite-Innovations%2F576939701%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
        {
            category: 'Lighting',
            attributes: ['lighting', 'light bulb', 'incadescent light bulb', 'light'], 
            customerRating: 0,
            customerRatingImage: 'http://i2.walmartimages.com/i/CustRating/0.gif',
            image: 'https://i5.walmartimages.com/asr/e967b20b-62fb-4b6c-aaae-3109a2a9a5ad_1.24dfd38fcec289365a641b51ba82a4fe.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff',
            name: 'Ushio 60w 120v PAR30 FL30 E26 Eco Plus PAR Xenon Halogen Light Bulb',
            price: 4.99,
            productId: 38273646,
            shortDescription: 'Ushio 60w 120v PAR30 FL30 E26 Eco Plus PAR Xenon Halogen Light Bulb',
            url: 'http://c.affil.walmart.com/t/api02?l=https%3A%2F%2Fwww.walmart.com%2Fip%2FUshio-60w-120v-PAR30-FL30-E26-Eco-Plus-PAR-Xenon-Halogen-Light-Bulb%2F38273646%3Faffp1%3DdjctSY0-vbCq6EFpleNL-_3vVVetoFFfMyPYp5WGbEA%26affilsrc%3Dapi%26veh%3Daff%26wmlspartner%3Dreadonlyapi',
        },
    ]);
};

export const Product = mongoose.model('Product', ProductSchema);

export interface IProduct {
    category: string;
    attributes: [string];
    customerRating: number;
    customerRatingImage: string;
    image: string;
    name: string;
    price: number;
    productId: number;
    shortDescription: string;
    url: string;
}
